config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "robots.:format" => "robots#robots"

  mount Blacklight::Engine => "/"
  mount BlacklightAdvancedSearch::Engine => "/"

  root to: "catalog#index"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: "catalog", path: "/catalog", controller: "catalog" do
    concerns :searchable
  end

  get "/catalog/:id/admin" => "catalog#admin", :as => "admin_catalog"

  devise_for :users

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: "/catalog", controller: "catalog" do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  mount Geoblacklight::Engine => "geoblacklight"
  concern :gbl_exportable, Geoblacklight::Routes::Exportable.new
  resources :solr_documents, only: [:show], path: "/catalog", controller: "catalog" do
    concerns :gbl_exportable
  end
  concern :gbl_wms, Geoblacklight::Routes::Wms.new
  namespace :wms do
    concerns :gbl_wms
  end
  concern :gbl_downloadable, Geoblacklight::Routes::Downloadable.new
  namespace :download do
    concerns :gbl_downloadable
  end
  resources :download, only: [:show]
  mount Blacklight::Allmaps::Engine => "/"
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true

require "blacklight/catalog"

class CatalogController < ApplicationController
  include BlacklightAdvancedSearch::Controller
  include Blacklight::Catalog

  configure_blacklight do |config|
    # Advanced config values
    config.advanced_search[:enabled] = true
    config.advanced_search ||= Blacklight::OpenStructWithHashAccess.new
    # config.advanced_search[:qt] ||= 'advanced'
    config.advanced_search[:url_key] ||= "advanced"
    config.advanced_search[:query_parser] ||= "edismax"
    config.advanced_search[:form_solr_parameters] ||= {}

    # Ensures that JSON representations of Solr Documents can be retrieved using
    # the path /catalog/:id/raw
    # Please see https://github.com/projectblacklight/blacklight/pull/2006/
    config.raw_endpoint.enabled = true

    # Blacklight::Allmaps Viewer
    config.default_solr_unique_key = "id"
    config.default_georeferenced_field = "gbl_georeferenced_b"

    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    ## @see https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html
    ## @see https://lucene.apache.org/solr/guide/6_6/the-dismax-query-parser.html#TheDisMaxQueryParser-Theq.altParameter
    config.default_solr_params = {
      :start => 0,
      "q.alt" => "*:*"
    }

    ## Default rows returned from Solr
    ## @see https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html
    config.default_per_page = 10

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    config.default_document_solr_params = {
      qt: "document",
      q: "{!raw f=#{Settings.FIELDS.ID} v=$id}"
    }

    # GeoBlacklight Defaults
    # * Adds the "map" split view for catalog#index
    config.view.split(partials: ["index"])
    config.view.delete_field("list")

    # solr field configuration for search results/index views
    # config.index.show_link = 'title_display'
    # config.index.record_display_type = 'format'

    config.index.title_field = Settings.FIELDS.TITLE

    # solr field configuration for document/show views
    # This sets the metadata to display below the map viewer.
    # To move metadata above the map viewer,
    # remove the lines deleting and re-adding the :show partial
    config.show.display_type_field = "format"
    config.show.partials.delete(:show)
    config.show.partials << "show_default_display_note"
    # config.show.partials << "show_default_viewer_container"

    # Blacklight::Allmaps Tabbed Viewer
    config.show.partials << "show_allmaps_tabbed_viewer_container"
    config.show.partials << "show_default_attribute_table"
    config.show.partials << "show_default_viewer_information"
    config.show.partials << :show

    ##
    # Configure the index document presenter.
    config.index.document_presenter_class = Geoblacklight::DocumentPresenter

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    # config.add_facet_field 'format', :label => 'Format'
    # config.add_facet_field 'pub_date', :label => 'Publication Year', :single => true
    # config.add_facet_field 'subject_topic_facet', :label => 'Topic', :limit => 20
    # config.add_facet_field 'language_facet', :label => 'Language', :limit => true
    # config.add_facet_field 'lc_1letter_facet', :label => 'Call Number'
    # config.add_facet_field 'subject_geo_facet', :label => 'Region'
    # config.add_facet_field 'solr_bbox', :fq => "solr_bbox:IsWithin(-88,26,-79,36)", :label => 'Spatial'
    # config.add_facet_field 'example_pivot_field', :label => 'Pivot Field', :pivot => ['format', 'language_facet']

    # config.add_facet_field 'example_query_facet_field', :label => 'Publish Date', :query => {
    #    :years_5 => { :label => 'within 5 Years', :fq => "pub_date:[#{Time.now.year - 5 } TO *]" },
    #    :years_10 => { :label => 'within 10 Years', :fq => "pub_date:[#{Time.now.year - 10 } TO *]" },
    #    :years_25 => { :label => 'within 25 Years', :fq => "pub_date:[#{Time.now.year - 25 } TO *]" }
    # }

    # FACETS

    # DEFAULT FACETS
    # to add additional facets, use the keys defined in the settings.yml file
    config.add_facet_field Settings.FIELDS.ACCESS_RIGHTS, label: "Access", limit: 5, collapse: false,
      item_component: Geoblacklight::IconFacetItemComponent
    config.add_facet_field Settings.FIELDS.SPATIAL_COVERAGE, label: "Place", limit: 5, collapse: false
    config.add_facet_field Settings.FIELDS.RESOURCE_CLASS, label: "Resource Class", limit: 5, collapse: false
    config.add_facet_field Settings.FIELDS.PROVIDER, label: "Provider", limit: 8, collapse: false,
      item_component: Geoblacklight::IconFacetItemComponent
    config.add_facet_field Settings.FIELDS.RESOURCE_TYPE, label: "Resource Type", limit: 10
    config.add_facet_field Settings.FIELDS.INDEX_YEAR, label: "Year", limit: 10
    config.add_facet_field Settings.FIELDS.FORMAT, label: "Format", limit: 10
    config.add_facet_field Settings.FIELDS.SUBJECT, label: "Subject", limit: 10
    config.add_facet_field Settings.FIELDS.THEME, label: "Theme", limit: 10
    config.add_facet_field Settings.FIELDS.CREATOR, label: "Creator", limit: 10
    config.add_facet_field Settings.FIELDS.PUBLISHER, label: "Publisher", limit: 10
    # config.add_facet_field Settings.FIELDS.GEOREFERENCED, label: "Georeferenced", limit: 3

    # GEOBLACKLIGHT APPLICATION FACETS

    # Map-Based "Search Here" Feature
    # item_presenter       - Defines how the facet appears in the GBL UI
    # filter_query_builder - Defines the query generated for Solr
    # filter_class         - Defines how to add/remove facet from query
    # label                - Defines the label used in contstraints container
    config.add_facet_field Settings.FIELDS.GEOMETRY, item_presenter: Geoblacklight::BboxItemPresenter,
      filter_class: Geoblacklight::BboxFilterField, filter_query_builder: Geoblacklight::BboxFilterQuery, within_boost: Settings.BBOX_WITHIN_BOOST, overlap_boost: Settings.OVERLAP_RATIO_BOOST, overlap_field: Settings.FIELDS.OVERLAP_FIELD, label: "Bounding Box"

    # Item Relationship Facets
    # * Not displayed to end user (show: false)
    # * Must be present for relationship "Browse all 4 records" links to work
    # * Label value becomes the search contraint filter name
    config.add_facet_field Settings.FIELDS.MEMBER_OF, label: "Member Of", show: false
    config.add_facet_field Settings.FIELDS.IS_PART_OF, label: "Is Part Of", show: false
    config.add_facet_field Settings.FIELDS.RELATION, label: "Related", show: false
    config.add_facet_field Settings.FIELDS.REPLACES, label: "Replaces", show: false
    config.add_facet_field Settings.FIELDS.IS_REPLACED_BY, label: "Is Replaced By", show: false
    config.add_facet_field Settings.FIELDS.SOURCE, label: "Source", show: false
    config.add_facet_field Settings.FIELDS.VERSION, label: "Is Version Of", show: false

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # SEARCH RESULTS FIELDS

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    # config.add_index_field Settings.FIELDS.PROVIDER, :label => 'Institution:'
    # config.add_index_field Settings.FIELDS.RIGHTS, :label => 'Access:'
    # # config.add_index_field 'Area', :label => 'Area:'
    # config.add_index_field Settings.FIELDS.SUBJECT, :label => 'Keywords:'
    config.add_index_field Settings.FIELDS.INDEX_YEAR
    config.add_index_field Settings.FIELDS.CREATOR
    config.add_index_field Settings.FIELDS.DESCRIPTION, helper_method: :snippit
    config.add_index_field Settings.FIELDS.PUBLISHER

    # ITEM VIEW FIELDS

    # solr fields to be displayed in the show (single result) view
    #  The ordering of the field names is the order of the display
    # item_prop: [String] property given to span with Schema.org item property
    # link_to_search: [Boolean] that can be passed to link to a facet search
    # helper_method: [Symbol] method that can be used to render the value

    # DEFAULT FIELDS
    # The following fields all feature string values. If there is a value present in the metadata, they fields will show up on the item show page.
    # The labels and order can be customed. Comment out fields to hide them.

    config.add_show_field Settings.FIELDS.ALTERNATIVE_TITLE, label: "Alternative Title", itemprop: "alt_title"

app/views/catalog/_document_split.html.erb
<div class='row'>
  <div id="documents" class="documents-list col-md-6">
    <%= render documents, :as => :document %>
  </div>
  <%= content_tag :div, '', id: 'map', class: 'col-md-6 sticky-top position-sticky', aria: { label: t('geoblacklight.map.label') }, data: { map: results_js_map_selector(controller.controller_name), 'catalog-path'=> search_catalog_path , 'map-bbox' => params[:bbox], basemap: geoblacklight_basemap, leaflet_options: leaflet_options } %>
</div>

app/views/catalog/_home_text.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-lg-5 order-1'>
      
      <div class='row text-center mb-4'>
        <div class='col-sm col-12 order-1'>         
          <div class='card mx-auto'>
            <h4 class='card-header facet-field-heading'>
              <%= link_to "Browse Datasets", "/?f[gbl_resourceClass_sm][]=Datasets" %>
            </h4>
          </div>
        </div>
        <div class='col-sm col-12 order-2'>         
          <div class='card mx-auto'>
            <h4 class='card-header facet-field-heading'>
              <%= link_to "Browse Maps", "/?f[gbl_resourceClass_sm][]=Maps" %>
            </h4>
          </div>
        </div>
      </div>

      <div class='row text-center mb-4'>
        <div class='col-sm col-12 order-3'>
          <div class='card mx-auto'>
            <h4 class='card-header facet-field-heading'>
              <%= link_to "AGSL Holdings", "/?f%5Bschema_provider_s%5D%5B%5D=American+Geographical+Society+Library+–+UWM+Libraries" %>
            </h4>
          </div>
        </div>
        <div class='col-sm col-12 order-4'>
          <div class='card mx-auto'> 
            <h4 class='card-header facet-field-heading'>
              <%= link_to "Wisconsin", "?f%5Bdct_spatial_sm%5D%5B%5D=Wisconsin" %>
            </h4>
          </div>
        </div>
      </div>

      <div class='row mb-4'>
        <div class='col-sm order-1'>
          <h4 class='sr-only'>Place</h4>
          <%= render_facet_partials [Settings.FIELDS.SPATIAL_COVERAGE], {class:'active'} %>
        </div>
        <div class='col-sm order-2'>
          <h4 class='sr-only'>Resource Class</h4>
          <%= render_facet_partials [Settings.FIELDS.RESOURCE_CLASS] %>
        </div>
      </div>

      <div class='row text-left'>
        <div class='col-md order-1 mb-3'> 
          <p>
            AGSL GeoDiscovery is an online geoportal that provides discovery and access to geospatial data for American Geographical Society Library patrons including open and restricted data in AGSL collections as well as data harvested from the <a href="https://opengeometadata.org/">OpenGeoMetadata</a> project. To learn more, check out our <a href="https://uwm.edu/libraries/agsl/agsl-geospatial-data/agsl-discovery-applications/about-geodiscovery/">about</a> and <a href="https://uwm.edu/libraries/agsl/agsl-geospatial-data/agsl-discovery-applications/about-geodiscovery/geodiscovery-help/">help</a> pages.
        </div>
      </div>
    </div>

    <div id="wrapper-map" class='col-lg-7 order-2'>
      <%= content_tag :div, '', id: 'map', aria: { label: t('geoblacklight.map.label') }, data: { map: 'home', 'catalog-path'=> search_catalog_path , 'map-geom' => Settings.HOMEPAGE_MAP_GEOM, basemap: geoblacklight_basemap, leaflet_options: leaflet_options } %>
    </div>
  </div>
</div>

app/views/catalog/_index_split_default.html.erb
<% # header bar for doc items in index view -%>
<%= content_tag :div, class: 'documentHeader row mb-4', data: { layer_id: document.id, geom: document.geometry.geojson } do %>
  <div class='col-md-12'>
    <div class='row'>
      <div class='col-2 thumbnail'>
        <% if document.sidecar.image.attached? %>
          <% if document.sidecar.image.variable? %>
            <%= image_tag document.sidecar.image.variant(resize: "200") %>
          <% else %>
            <%= image_tag document.sidecar.image %>
          <% end %>
        <% else %>
          <span class="icon square" title="<%=document[Settings.FIELDS.RESOURCE_CLASS]%>">
            <%= geoblacklight_icon(document[Settings.FIELDS.RESOURCE_CLASS].first) %>
          </span>
        <% end %>
      </div>
      <div class='col-9'>
        <h3 class="index_title text-span">
          <% counter = document_counter_with_offset(document_counter) %>
          <span class="document-counter">
            <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
          </span>
          <%= link_to_document document, counter: counter, itemprop: "name" %>
        </h3>
        <small>
          <div class='status-icons'>
            <%= render partial: 'header_icons', locals: { document: document } %>
          </div>
          <%= geoblacklight_present(:index_fields_display, document) %>
        </small>
      </div>
    </div>
  </div>
<% end %>

app/views/catalog/_search_form.html.erb
<%= warn "#{__FILE__} is a deprecated partial." %>
<%= render((blacklight_config&.view_config(document_index_view_type)&.search_bar_component || Blacklight::SearchBarComponent).new(
      url: search_action_url,
      advanced_search_url: search_action_url(action: 'advanced_search'),
      params: search_state.params_for_search.except(:qt),
      search_fields: Deprecation.silence(Blacklight::ConfigurationHelperBehavior) { search_fields },
      autocomplete_path: search_action_path(action: :suggest))) %>



<div>
  <%= link_to 'More options', blacklight_advanced_search_engine.advanced_search_path(search_state.to_h), class: 'advanced_search'%>
</div>

app/views/catalog/admin.html.haml
%h3=@document[blacklight_config.index.title_field]

%table.table.table-borderless.table-sm
  %thead
    %tr
      %th Provenance
      %th Indexed

  %tbody
    %tr
      %td= @document._source['schema_provider_s']
      %td= DateTime.parse(@document._source['timestamp']).strftime('%D %r')
%hr

%h3 SolrDocument
%div.solr-document
  != ap @document.to_h

%br
%h3 Item Viewer
%table.table
  %thead
    %tr
      %th Protocol
      %th Endpoint
  %tbody
    %tr
      %td= @document.viewer_protocol
      %td= link_to(@document.viewer_endpoint, @document.viewer_endpoint)

%h3 Thumbnail
%table.table
  %thead
    %tr
      %th Display
      %th Attached
      %th State
      %th Last Transition
  %tbody
    %tr
      - if @document.sidecar.image.attached?
        %td
          %div.media
            %span.mr-3
              = image_tag @document.sidecar.image, { height: "200px" }
      - else
        %td
          %div.media
            %span.icon.square.mr-3= geoblacklight_icon(@document[Settings.FIELDS.GEOM_TYPE], classes: 'svg_tooltip')

      %td= @document.sidecar.image.attached?
      %td= @document.sidecar.image_state.current_state
      %td
        - if @document.sidecar.image_state.last_transition
          = @document.sidecar.image_state.last_transition.metadata

:javascript
  new Readmore( '.solr-document', { maxHeight: 40 } );